name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  autoconf_ver: 2.69

jobs:
  autoconf:
    runs-on: ubuntu-latest
    container: ubuntu:21.04

    steps:
    - uses: actions/checkout@v2
    - name: install autoconf
      run: |
        apt-get update -y -qq
        apt-get install -y -qq build-essential autoconf${{ env.autoconf_ver }}
    - name: run autoreconf
      run: |
        autoreconf${{ env.autoconf_ver }} -fi
    - uses: actions/upload-artifact@v2
      with:
        name: configure
        path: |
          configure
          include/HsNetworkConfig.h.in

  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    needs: autoconf

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.0', '8.2', '8.4', '8.6', '8.8', '8.10.4']
        exclude:
        - os: windows-latest
          ghc: "8.0"
        - os: windows-latest
          ghc: "8.2"
        - os: windows-latest
          ghc: "8.4"
        - os: windows-latest
          ghc: "8.6"
        - os: windows-latest
          ghc: "8.10"
        - os: macOS-latest
          ghc: "8.0"
        - os: macOS-latest
          ghc: "8.2"
        - os: macOS-latest
          ghc: "8.4"
        - os: macOS-latest
          ghc: "8.6"
        - os: macOS-latest
          ghc: "8.8"

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.4'

    - uses: actions/download-artifact@v2
      with:
        name: configure

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: matrix.os != 'windows-latest'
      run: |
        sh ./enable_doctest.sh

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --disable-benchmarks
    - name: Build
      run: |
        cabal build --enable-tests --disable-benchmarks all
    - name: Run tests
      run: cabal test all
